# Introduction à NumPy

NumPy est une bibliothèque pour le calcul scientifique en Python. Elle permet de manipuler des tableaux multidimensionnels et offre des fonctions mathématiques optimisées.

In [1]:
import numpy as np

# Création d'un tableau NumPy simple
array1 = np.array([1, 2, 3, 4, 5])
print("Tableau NumPy :", array1)

Tableau NumPy : [1 2 3 4 5]


In [2]:
# Création d'une matrice NumPy
matrice1 = np.array([[1, 2, 3], [4, 5, 6]])
print("\nMatrice NumPy :\n", matrice1)


Matrice NumPy :
 [[1 2 3]
 [4 5 6]]


In [3]:
# Création d'un tableau de zéros
zeros = np.zeros((3, 3))  # Matrice de zéros 3x3
print("\nMatrice de zéros :\n", zeros)


Matrice de zéros :
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
# Création d'un tableau de uns
uns = np.ones((2, 2))  # Matrice de uns 2x2
print("\nMatrice de uns :\n", uns)


Matrice de uns :
 [[1. 1.]
 [1. 1.]]


In [5]:
# Création d'un tableau de valeurs aléatoires
aleatoire = np.random.rand(3, 3)  # Matrice 3x3 de valeurs aléatoires entre 0 et 1
print("\nMatrice aléatoire :\n", aleatoire)


Matrice aléatoire :
 [[0.90421987 0.00302726 0.32304495]
 [0.08443704 0.95228194 0.35329768]
 [0.28548586 0.40813912 0.57152835]]


In [6]:
# Opérations de base sur les tableaux NumPy
array2 = np.array([10, 20, 30, 40, 50])
print("\nSomme des deux tableaux :", array1 + array2)
print("Produit des deux tableaux :", array1 * array2)


Somme des deux tableaux : [11 22 33 44 55]
Produit des deux tableaux : [ 10  40  90 160 250]


In [7]:
# Calculs statistiques
print("\nMoyenne du tableau :", np.mean(array1))
print("Somme du tableau :", np.sum(array1))
print("Écart-type du tableau :", np.std(array1))


Moyenne du tableau : 3.0
Somme du tableau : 15
Écart-type du tableau : 1.4142135623730951


In [8]:
# Opérations sur les matrices
matrice2 = np.array([[7, 8, 9], [10, 11, 12]])
print("\nAddition de matrices :\n", matrice1 + matrice2)
print("Multiplication élément par élément :\n", matrice1 * matrice2)


Addition de matrices :
 [[ 8 10 12]
 [14 16 18]]
Multiplication élément par élément :
 [[ 7 16 27]
 [40 55 72]]


In [9]:
# Produit matriciel
produit_matriciel = np.dot(matrice1, matrice2.T)  # Produit matriciel avec la transposée
print("\nProduit matriciel :\n", produit_matriciel)


Produit matriciel :
 [[ 50  68]
 [122 167]]


In [10]:
# Extraction de sous-matrices
print("\nSous-matrice (première ligne) :", matrice1[0, :])
print("Sous-matrice (première colonne) :", matrice1[:, 0])


Sous-matrice (première ligne) : [1 2 3]
Sous-matrice (première colonne) : [1 4]


In [11]:
# Reshape et Transposition
matrice3 = np.arange(1, 10).reshape((3, 3))
print("\nMatrice reshape :\n", matrice3)
print("\nTransposée de la matrice :\n", matrice3.T)


Matrice reshape :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Transposée de la matrice :
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
