## Analyse des Performances des Joueurs avec NumPy
Cet exercice consiste à manipuler des tableaux NumPy pour analyser les performances des joueurs d'un jeu vidéo.

In [1]:
import numpy as np

# Génération de données fictives : scores de 100 joueurs sur 5 niveaux
data = np.random.randint(0, 101, (100, 5))  # Scores entre 0 et 100

### 1. Calcul de la moyenne des scores de chaque joueur

In [2]:
player_averages = np.mean(data, axis=1)
print("Moyenne des scores par joueur:", player_averages)

Moyenne des scores par joueur: [36.  45.2 53.  60.4 63.4 75.  43.2 64.  44.6 68.6 42.  41.4 73.6 54.4
 49.6 66.  48.2 36.8 65.4 45.  58.2 51.4 68.4 52.6 50.6 32.6 54.4 41.4
 54.2 44.4 43.4 54.2 48.8 51.2 52.  39.4 50.2 67.  49.  45.6 47.4 41.2
 36.2 61.4 44.6 69.4 45.8 54.  50.  43.2 54.  30.6 64.6 38.2 57.4 22.6
 34.6 36.6 62.2 46.2 41.  44.2 35.8 24.  64.8 44.6 53.8 72.  60.8 50.2
 43.2 43.6 36.  44.4 57.2 53.4 55.2 44.6 46.4 53.2 48.2 55.4 66.6 66.4
 55.6 61.6 51.4 65.2 53.4 59.8 69.4 32.2 52.4 24.2 55.4 45.8 68.2 75.
 31.6 34.2]


### 2. Score maximum et minimum par niveau

In [3]:
max_scores_per_level = np.max(data, axis=0)
min_scores_per_level = np.min(data, axis=0)
print("Max scores par niveau:", max_scores_per_level)
print("Min scores par niveau:", min_scores_per_level)

Max scores par niveau: [ 99 100 100 100 100]
Min scores par niveau: [1 2 0 1 2]


### 3. Déterminer le meilleur joueur en score total

In [4]:
total_scores = np.sum(data, axis=1)
best_player = np.argmax(total_scores)
print("Le meilleur joueur est le numéro:", best_player)

Le meilleur joueur est le numéro: 5


### 4. Normalisation des scores entre 0 et 1

In [5]:
norm_data = (data - np.min(data)) / (np.max(data) - np.min(data))
print("Scores normalisés:", norm_data)

Scores normalisés: [[0.65 0.03 0.82 0.12 0.18]
 [0.17 0.61 0.85 0.05 0.58]
 [0.97 0.67 0.24 0.39 0.38]
 [0.47 0.71 0.14 0.84 0.86]
 [0.58 0.55 0.58 0.87 0.59]
 [0.97 0.7  0.94 0.59 0.55]
 [0.87 0.2  0.04 0.24 0.81]
 [0.72 0.88 1.   0.37 0.23]
 [0.41 0.83 0.18 0.48 0.33]
 [0.9  0.5  0.28 0.91 0.84]
 [0.03 0.34 0.78 0.09 0.86]
 [0.42 0.02 0.08 0.98 0.57]
 [0.89 0.82 0.97 0.83 0.17]
 [0.6  0.95 0.41 0.41 0.35]
 [0.56 0.8  0.1  0.57 0.45]
 [0.77 0.86 0.27 0.6  0.8 ]
 [0.29 0.13 0.27 0.98 0.74]
 [0.91 0.02 0.27 0.19 0.45]
 [0.45 0.22 0.9  0.86 0.84]
 [0.12 0.08 0.68 0.9  0.47]
 [0.86 0.54 0.55 0.16 0.8 ]
 [0.85 0.17 0.87 0.04 0.64]
 [0.29 0.95 0.31 0.87 1.  ]
 [0.43 0.87 0.26 0.12 0.95]
 [0.16 0.62 0.48 0.48 0.79]
 [0.13 0.23 0.33 0.41 0.53]
 [0.04 0.62 0.71 0.69 0.66]
 [0.4  0.61 0.39 0.2  0.47]
 [0.52 0.68 0.   0.83 0.68]
 [0.92 0.61 0.14 0.3  0.25]
 [0.39 0.68 0.54 0.09 0.47]
 [0.6  0.89 0.47 0.37 0.38]
 [0.48 0.73 0.62 0.5  0.11]
 [0.74 0.85 0.6  0.22 0.15]
 [0.93 0.08 0.6  0.28 0.71]
 

### 5. Filtrer les joueurs ayant un score moyen supérieur à 70

In [6]:
high_performers = data[np.mean(data, axis=1) > 70]
print("Joueurs avec une moyenne > 70:", high_performers)

Joueurs avec une moyenne > 70: [[ 97  70  94  59  55]
 [ 89  82  97  83  17]
 [  1  79  99 100  81]
 [ 39  93  97  52  94]]


### 6. Ajouter un handicap de -5 points aux joueurs ayant un score max > 90

In [7]:
data[data > 90] -= 5
print("Scores après handicap:", data)

Scores après handicap: [[65  3 82 12 18]
 [17 61 85  5 58]
 [92 67 24 39 38]
 [47 71 14 84 86]
 [58 55 58 87 59]
 [92 70 89 59 55]
 [87 20  4 24 81]
 [72 88 95 37 23]
 [41 83 18 48 33]
 [90 50 28 86 84]
 [ 3 34 78  9 86]
 [42  2  8 93 57]
 [89 82 92 83 17]
 [60 90 41 41 35]
 [56 80 10 57 45]
 [77 86 27 60 80]
 [29 13 27 93 74]
 [86  2 27 19 45]
 [45 22 90 86 84]
 [12  8 68 90 47]
 [86 54 55 16 80]
 [85 17 87  4 64]
 [29 90 31 87 95]
 [43 87 26 12 90]
 [16 62 48 48 79]
 [13 23 33 41 53]
 [ 4 62 71 69 66]
 [40 61 39 20 47]
 [52 68  0 83 68]
 [87 61 14 30 25]
 [39 68 54  9 47]
 [60 89 47 37 38]
 [48 73 62 50 11]
 [74 85 60 22 15]
 [88  8 60 28 71]
 [30 43 33 16 75]
 [68 22 53 49 59]
 [74 59 86 21 90]
 [39 40 66 76 24]
 [75 39 19 50 45]
 [87 68 18 46 18]
 [65 52 42 25 22]
 [38 52 33 30 28]
 [19 67 77 58 86]
 [15 55 41 80 32]
 [38 68 68 74 94]
 [89 25  6 54 50]
 [40 71 82 41 36]
 [14 78 90 18 50]
 [ 2 79 29  7 94]
 [16 43 90 40 76]
 [47 39 13 11 43]
 [90 14 87 84 43]
 [ 5 39 42 74 31]
 [31 

### 7. Restructurer le tableau en ajoutant une colonne d'identifiant des joueurs

In [8]:
player_ids = np.arange(1, 101).reshape(100, 1)
data_with_ids = np.hstack((player_ids, data))
print("Données avec ID joueurs:", data_with_ids)

Données avec ID joueurs: [[  1  65   3  82  12  18]
 [  2  17  61  85   5  58]
 [  3  92  67  24  39  38]
 [  4  47  71  14  84  86]
 [  5  58  55  58  87  59]
 [  6  92  70  89  59  55]
 [  7  87  20   4  24  81]
 [  8  72  88  95  37  23]
 [  9  41  83  18  48  33]
 [ 10  90  50  28  86  84]
 [ 11   3  34  78   9  86]
 [ 12  42   2   8  93  57]
 [ 13  89  82  92  83  17]
 [ 14  60  90  41  41  35]
 [ 15  56  80  10  57  45]
 [ 16  77  86  27  60  80]
 [ 17  29  13  27  93  74]
 [ 18  86   2  27  19  45]
 [ 19  45  22  90  86  84]
 [ 20  12   8  68  90  47]
 [ 21  86  54  55  16  80]
 [ 22  85  17  87   4  64]
 [ 23  29  90  31  87  95]
 [ 24  43  87  26  12  90]
 [ 25  16  62  48  48  79]
 [ 26  13  23  33  41  53]
 [ 27   4  62  71  69  66]
 [ 28  40  61  39  20  47]
 [ 29  52  68   0  83  68]
 [ 30  87  61  14  30  25]
 [ 31  39  68  54   9  47]
 [ 32  60  89  47  37  38]
 [ 33  48  73  62  50  11]
 [ 34  74  85  60  22  15]
 [ 35  88   8  60  28  71]
 [ 36  30  43  33  16  75]
 [ 

### 8. Sauvegarde des données dans un fichier CSV

In [9]:
np.savetxt("../player_scores.csv", data_with_ids, delimiter=",", header="ID,Niveau1,Niveau2,Niveau3,Niveau4,Niveau5", comments='')
print("Données sauvegardées dans player_scores.csv")

Données sauvegardées dans player_scores.csv
